config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'blogs#index'
  resources :users, only: [:edit, :update]
  resources :blogs, except: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # deviseコントローラ上のアクションが動いた場合のみ befor actionのストロングパラメーターをうごかす。(deviseファイルに直接記述できないため)
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  
  #ユーザーがサインインしているかを確認する
  #サインインしていない場合は、index画面にリダイレクト
  before_action :move_to_index, except: [:index]

  def index
    @blogs = Blog.includes(:user).order("created_at DESC")
  end

  def new
    # newのビュー画面でform_forを使用するためにインスタンス変数をここに宣言
    @blog = Blog.new
  end

  def create
    Blog.create(blog_params)
    # 投稿完了後はindexアクションを実行し、index画面にリダイレクトする。
    redirect_to action: :index
  end

  def edit
    # binding.pry
    @blog = Blog.find(params[:id])
  end

  def update
    blog = Blog.find(params[:id])
    # ブログのidと現在のuseridチェック
    if blog.user_id == current_user.id
      blog_params.delete(:user_id)
      blog.update(blog_params)

    # 投稿完了後はindexアクションを実行し、index画面にリダイレクトする。
    end
    redirect_to action: :index
  end

  # ブログの削除
  def destroy
    blog = Blog.find(params[:id])
    if blog.user_id == current_user.id
      blog.destroy
    end
    # 最新の情報を表示するためにindexアクションにリダイレクト
    redirect_to action: :index
  end

  private 
  def blog_params
    params.require(:blog).permit(:title, :content).merge(user_id: current_user.id)
  end

  #サインインしていない場合、インデックスページに遷移する
  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_blog-header.html.erb
<div　class = 'header'>
  <div class= 'main-header'>
    <div class = 'main-header__logo'>
      <%= link_to 'Blog' ,root_path %>
    </div>
    <div class = 'main-header__user-name'>
      <%if request.url == "http://localhost:3000/users/sign_in" %>
        <span>Sign in</span>
      <% elsif request.url == "http://localhost:3000/users/sign_up" %>
        <span>Sign up</span>
      <% elsif !user_signed_in? %>
        ゲストさん、いらっしゃい！
      <% else %>
        <%= current_user.name %>さん、ごゆるりと〜
      <% end %>
    </div>
    <ul class = 'header-function'>
      <%# ユーザーがサインインしている婆に表示する  %>
      <% if !user_signed_in? && !request.url.start_with?("http://localhost:3000/users")%>
      <li class = 'header-function__sign-in'>
        <%= link_to 'SignIn' ,new_user_session_path %>
      </li>
      <% elsif user_signed_in? && !request.url.start_with?("http://localhost:3000/users")%>
      <li class = 'header-function__signOut'>
        <%= link_to 'SignOut' ,destroy_user_session_path, method: :delete %>
      </li>
      <li class = 'header-function__create-blog'>
        <%= link_to 'New' , new_blog_path%>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/blogs/_blog.html.erb
<div class = 'blog'>
  <div class = 'blog__text'>
    <p>投稿者 : <%= blog.user.name%></p>
    <p>タイトル : <%= blog.title%></p>
    <%= blog.content%>
  </div>
  <%# ユーザーがサインインしている場合と  %>
  <%# ユーザーがサインインいているidとブログを作成したユーザーidが一致している場合に表示する  %>
  <%if user_signed_in? && current_user.id == blog.user_id%>
    <ul class = 'blog-function'>
      <%# <li class = 'blog-function__show'>
        <%= link_to 'Show' %>
      <%# </li>  %>
      <li class = 'blog-function__edit'>
        <%= link_to 'Edit', edit_blog_path(blog)%>
      </li>
      <li class = 'blog-function__destroy'>
        <%= link_to 'Destroy', blog_path(blog), method: :delete, data: { confirm: 'Really?'} %>
      </li>
    </ul>
  <%end%>
</div>

app/views/blogs/edit.html.erb
<%= render "blog-header"%>
<div class = 'contents'>
  <%= form_for (@blog), html: {class: 'new-blog'} do |f|%>
    <h2>ブログを投稿してください</h2>
    <div class = new-blog__title>
      <%= f.label :タイトル %><br>
      <%= f.text_field :title, class: 'new-blog__title__input'%>
    </div>
    <div class = new-blog__content>
      <%= f.label :ブログ %><br>
      <%= f.text_area :content, class: 'new-blog__content__input' %>
    </div>
    <%= f.submit '送信', class: 'new-blog__submit-btn'%>
  <%end%>
</div>

app/views/blogs/index.html.erb
<%= render "blog-header"%>
<div class = 'contents'>
  <%= render partial: 'blog', collection: @blogs%>
<div>

app/views/blogs/new.html.erb
<%= render "blog-header"%>
<div class = 'contents'>
  <%= form_for (@blog), html: {class: 'new-blog'} do |f|%>
    <h2>ブログを投稿してください</h2>
    <div class = new-blog__title>
      <%= f.label :タイトル %><br>
      <%= f.text_field :title, class: 'new-blog__title__input'%>
    </div>
    <div class = new-blog__content>
      <%= f.label :ブログ %><br>
      <%= f.text_area :content, class: 'new-blog__content__input' %>
    </div>
    <%= f.submit '送信', class: 'new-blog__submit-btn'%>
  <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>